PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entity ?type
WHERE {
  VALUES ?type {
    owl:Class
    owl:ObjectProperty
    owl:DatatypeProperty
    owl:AnnotationProperty
    owl:NamedIndividual
  }
  ?entity rdf:type ?type .
  FILTER(isIRI(?entity))
  FILTER NOT EXISTS { ?entity rdfs:label ?label }
}
ORDER BY ?entity
