PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entity ?parent
WHERE {
  {
    ?entity a owl:Class ;
      rdfs:subClassOf ?parent .
  }
  UNION
  {
    ?entity a ?property_type ;
      rdfs:subPropertyOf ?parent .
    VALUES ?property_type {
      owl:ObjectProperty
      owl:DatatypeProperty
      owl:AnnotationProperty
    }
  }
  FILTER(isIRI(?entity))
  FILTER(isIRI(?parent))
  FILTER NOT EXISTS { ?parent rdfs:label ?parent_label }
}
ORDER BY ?entity ?parent
